#!/bin/sh
# Detect AC power or not in a portable way
# Exit 0 if on AC power, 1 if not and 255 if we don't know how to work it out

# Copyright (c) 2007-2015 The OpenRC Authors.
# See the Authors file at the top-level directory of this distribution and
# https://github.com/OpenRC/openrc/blob/master/AUTHORS
#
# This file is part of OpenRC. It is subject to the license terms in
# the LICENSE file found in the top-level directory of this
# distribution and at https://github.com/OpenRC/openrc/blob/master/LICENSE
# This file may not be copied, modified, propagated, or distributed
#    except according to the terms contained in the LICENSE file.

if [ -f /proc/acpi/ac_adapter/ ]; then
        if [ "$(find /proc/acpi/ac_adapter/ -maxdepth 1 -mindepth 1 -type d | wc -l)" -gt 1 ]; then
                echo "WARNING: more than one ac adapter found!"
        fi

	for adapter in proc/acpi/ac_adapter/*/state; do
                while read -r line; do
                        case "$line" in
			"state:"*"off-line") exit 128;;
		        esac
                done < "$adapter"
	done
elif [ -f /sys/class/power_supply/ ]; then
        if [ "$(find  /sys/class/power_supply/ -maxdepth 1 -mindepth 1 -type d | wc -l)" -gt 1 ]; then
                echo "WARNING: more than one power supply found!"
        fi
        for adapter in /sys/class/power_supply/*/online; do
                while read -r line; do
		        [ "${line}" = 0 ] && exit 128
	        done
        done

elif [ -f /proc/pmu/info ]; then
	while read -r line; do
		case "$line" in
		"AC Power"*": 0") exit 128;;
		esac
	done < /proc/pmu/info
elif command -v envstat >/dev/null 2>&1; then
	# NetBSD has envstat
	envstat -d acpiacad0 2>/dev/null | while read -r line; do
		case "$line" in
		"connected:"*"OFF") exit 128;;
		esac
	done
elif sysctl -q hw.acpi.acline >/dev/null 2>/dev/null; then
	case $(sysctl -n hw.acpi.acline) in
	0) exit 1;;
	*) exit 0;;
	esac
else
	exit 255
fi
[ $? != 128 ]
